export const FETCHING_CLIENTS = 'FETCH_CLIENTS';
export const FETCHING_CLIENTS_SUCCESSFULLY = 'FETCHING_CLIENTS_SUCCESSFULLY';
export const FETCHING_CLIENTS_ERROR = 'FETCHING_CLIENTS_ERROR';
export const ADD_CLIENT = 'ADD_CLIENT';
export const ADD_CLIENT_SUCCESSFULLY = 'ADD_CLIENT_SUCCESSFULLY';
export const ADD_CLIENT_ERROR = 'ADD_CLIENT_ERROR';
